### ISSUE TITLE
Negative values are not processed properly

### ISSUE THREAD

**Issue by Sum80** [stvmyr/freeD#3]
Hi i ported your code to c++ and when negative  values are sent than it does not convert them function like GetPosition does not convert it correctly. I am working on little endian system can that be a issue ?

**Comment by stvmyr** [comment]
Hi There! 
Do you got problems with your c++ implementation, or my golang code?
Where comes your sample data from? Are you sure that the data is valid?
Depending on how you do it, Little Endian shouldn't be a problem...

I've tested my library with multiple systems and got no problems at all. But if there is an error I can replicate, i'm happy to help!

I'm currently working on a port of my code to c++ too. But I've got too little time at the moment to test ist properly.

**Comment by Sum80** [comment]
These are the functions in c++ from your code.

float GetRotation(std::vector<std::byte> &data, int offset) const
	{
		return float(int32_t(data[ offset + 0]) << 24 | int32_t(data[offset + 1]) << 16 | int32_t(data[offset + 2]) << 8) / 32768 / 256;
	}

	float GetPosition(const std::vector<std::byte>& data, int offset)
	{
		return float(int32_t(data[0]) << 24 | int32_t(data[1]) << 16 | int32_t(data[2]) << 8) / 64 / 256;		
	}

**Comment by stvmyr** [comment]
Your functions will only work with positive values on an little endian system. Hope that helps.

Here are the functions of my c++ implementation. They are tested with positiv and negative values on an little endian system. 

`float getPosition(const char* data) {
    int32_t value = 0;
    value |= static_cast<int32_t>(static_cast<uint8_t>(data[0])) << 24;
    value |= static_cast<int32_t>(static_cast<uint8_t>(data[1])) << 16;
    value |= static_cast<int32_t>(static_cast<uint8_t>(data[2])) << 8;
    return static_cast<float>(value) / 64 / 256;
}`

`float GetRotation(const char* data) {
    int32_t value = 0;
    value |= static_cast<int32_t>(static_cast<uint8_t>(data[0])) << 24;
    value |= static_cast<int32_t>(static_cast<uint8_t>(data[1])) << 16;
    value |= static_cast<int32_t>(static_cast<uint8_t>(data[2])) << 8;
    return static_cast<float>(value) / 32768.0f / 256.0f;
}`

**Comment by Sum80** [comment]
Thank you very much for the code , Really appreciate your kind help.

Just one last this thing could you please look into my GetEncoder function

```
int getEncoder(std::vector<char>& data_, int offset) {
		std::vector<char> data;
		data.push_back(data_[offset]);
		data.push_back(data_[offset + 1]);
		data.push_back(data_[offset + 2]);
		data.push_back(data_[offset + 3]);
		std::vector<char> value{ '\0', '\0', '\0', '\0' };
		std::copy(data.begin(), data.end(), std::back_inserter(value));
		uint32_t temp = (static_cast<uint32_t>(value[0]) << 24) | (static_cast<uint32_t>(value[1]) << 16) | (static_cast<uint32_t>(value[2]) << 8 );
		int result;
		std::memcpy(&result, &temp, sizeof(temp));
		return result;
	}
```
